// TODO: Replace this file with the actual firebase_options.dart generated by `flutterfire configure`
// or manually populate the keys.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return DefaultFirebaseOptions.web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return DefaultFirebaseOptions.windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAREedrHpB0CCyn_WgUjuWyi9AewVQ-l4A',
    appId: '1:415585262962:web:7bbc1c0c92c72eef7d11eb',
    messagingSenderId: '415585262962',
    projectId: 'reading-jesus-somang',
    authDomain: 'reading-jesus-somang.firebaseapp.com',
    storageBucket: 'reading-jesus-somang.firebasestorage.app',
    measurementId: 'G-MSCT2Q04SE',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAREedrHpB0CCyn_WgUjuWyi9AewVQ-l4A',
    appId: '1:415585262962:web:7bbc1c0c92c72eef7d11eb',
    messagingSenderId: '415585262962',
    projectId: 'reading-jesus-somang',
    authDomain: 'reading-jesus-somang.firebaseapp.com',
    storageBucket: 'reading-jesus-somang.firebasestorage.app',
    measurementId: 'G-MSCT2Q04SE',
  );
}
